spring.application.name=bookHub

# Database Connection
spring.datasource.url=jdbc:sqlserver://localhost;databasename=BookHub;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=MonSuperMotDePasse123!

#Détail des requêtes pour le développement
spring.jpa.show-sql=true
# Automatically creates tables for easier development
spring.jpa.hibernate.ddl-auto=update

#Internationalization = i18n
#Message bundles encoding
spring.messages.encoding=utf-8
spring.web.locale=en

# Should be set to "false" in production
# When set to "false", should deal with LazyInitializationException errors :
# Must ensure all necessary data is fetched inside
# Service layer (using JOIN FETCH queries, @EntityGraph,
# or mapping to DTOs) before returning the object to the Controller.
spring.jpa.open-in-view=true