# 1. CHARGE .env AUTO
spring.config.import=optional:file:.env[.properties]

spring.application.name=bookHub

# Database sensibles ? .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Dev settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# i18n
spring.messages.encoding=utf-8
spring.web.locale=en

# Security sensibles ? .env

security.jwt.expiration-seconds=${JWT_EXPIRATION} 

security.jwt.secret=${JWT_SECRET}
